name: Protocol tests

on:
  push:
  pull_request:

jobs:
  protocol-tests:
    runs-on: ubuntu-latest

    container:
      image: espressif/idf:v6.0.2

    steps:
      - name: Run protocol tests
        shell: bash
        run: |
          source "$IDF_PATH/export.sh"
          apt-get update
          apt-get install -y libbsd-dev
          python -m pip install -r tests/protocol/requirements.txt
          cd tests/protocol
          idf.py --preview set-target linux
          idf.py build
          python -m pytest
